package main.kotlin.amaze.puzzles

val puzzles = listOf(
    """
        XXXXXXX
        XXXDXXX
        XXXOXXX
        XXXOXXX
        XXXOXXX
        XXXSXXX
        XXXXXXX
    """.trimIndent(),
    """
        XXXXXXX
        XOOOODX
        XOXXXXX
        XSXXXXX
        XXXXXXX
    """.trimIndent(),
    """
        XXXXXXX
        XXXDXXX
        XXXOXXX
        XXXOXXX
        XXXOXXX
        XSOOOSX
        XXXXXXX
    """.trimIndent(),
    """
        XXXXXXXXXXX
        XOOOOOOOOOX
        XOXOXOXOXOX
        XOXOXOXOXOX
        XSXPXDXPXSX
        XXXXXXXXXXX
    """.trimIndent(),
    """
        XXXXXXXXXXXXXX
        XDOXXXXXOOOOOX
        XXOOOOOOOOXXOX
        XXOOPOXXXOXOOX
        XXXXXXPXOOXXXX
        XXXOOOOOOOXXXX
        XPOOOOSXXOOOOX
        XXXXXXXXXXXXXX
    """.trimIndent(),
    """
        XXXXXXXXXXXXXXXXXXXX
        XDOOOOOOOOPOOOOOOOOX
        XPXXXXOXPOXOXXXXOXOX
        XOXXOOOXXXXXOOOOXXOX
        XOOOXXOOOOOXOXXOXXOX
        XOXXXXXXXXOOXOOOOOOX
        XOOOOOOXXXXOOOXOXPOX
        XXXXXOXOOOXXXXXOXXOX
        XOOOXOOOXXXOXXXOOOXX
        XOXOXXXOOOOOOOXXXOOX
        XOOOOOOOXXSXXOOOOOXX
        XXXXXXXXXXXXXXXXXXXX
    """.trimIndent(),
    """
        XXXXXXXXXXXXXX
        XXOOOOOOOOOPFX
        XXDXXXXXXXOOOX
        XXXXXXXXXXXXXX
        XXXXXOOOOOOXFX
        XSOOOOXOXXOOOX
        XXXXXXXXXXXXXX
    """.trimIndent(),
    """
        XXXXXXXXXXXXXX
        XXXXXOOOOOOFXX
        XXOOOXXXXXXXXX
        XXOGOOOOOOOXXX
        XXODXPPXXXFOOX
        XXXXXOOOOOOXOX
        XSSSOOOOOXXXGX
        XXXXXXXXXXXXXX
    """.trimIndent(),
    """
        XXXXXXXXXXXXXX
        XSOXOOOXPGXPFX
        XXOOOXOOOOPOOX
        XXXXXXXXXOOOXX
        XFXOOOOPXXXXXX
        XOOOXXDPXPOOOX
        XXXXXXOOOOXXHX
        XXOOOXXXXXXXXX
        XOOPOOOOXOOOXX
        XGPXHPXOOOXOSX
        XXXXXXXXXXXXXX
    """.trimIndent(),
    """
        XXXXXXXXXXXXXX
        XSOOSOOOOSOOSX
        XOOOOOSOOOOOOX
        XSOXXXXXXXXOOX
        XOOOOOOOOOOOOX
        XOOOXXOOXXOOOX
        XOOOXFOGPXOOSX
        XSOOXDGPFXOOOX
        XOOOXXXXXXXOOX
        XOSOSOOOOSOSOX
        XSOOOOSOOOOOSX
        XXXXXXXXXXXXXX
    """.trimIndent()
)
