package main.kotlin.amaze.puzzles

import main.kotlin.amaze.entity.VanishingWalkwayPattern
import main.kotlin.amaze.entity.VanishingWalkwayState
import main.kotlin.amaze.entity.VanishingWalkwayState.*

val puzzles = listOf(
    PuzzleDefinition("""
        XXXXXXX
        XXXDXXX
        XXXOXXX
        XXXOXXX
        XXXOXXX
        XXXSXXX
        XXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXX
        XOOOODX
        XOXXXXX
        XSXXXXX
        XXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXX
        XXXDXXX
        XXXOXXX
        XXXOXXX
        XXXOXXX
        XSOOOSX
        XXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXXXXXX
        XOOOOOOOOOX
        XOXOXOXOXOX
        XOXOXOXOXOX
        XSXPXDXPXSX
        XXXXXXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXXXXXXXXX
        XDOXXXXXOOOOOX
        XXOOOOOOOOXXOX
        XXOOPOXXXOXOOX
        XXXXXXPXOOXXXX
        XXXOOOOOOOXXXX
        XPOOOOSXXOOOOX
        XXXXXXXXXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXXXXXXXXXXXXXXX
        XDOOOOOOOOPOOOOOOOOX
        XPXXXXOXPOXOXXXXOXOX
        XOXXOOOXXXXXOOOOXXOX
        XOOOXXOOOOOXOXXOXXOX
        XOXXXXXXXXOOXOOOOOOX
        XOOOOOOXXXXOOOXOXPOX
        XXXXXOXOOOXXXXXOXXOX
        XOOOXOOOXXXOXXXOOOXX
        XOXOXXXOOOOOOOXXXOOX
        XOOOOOOOXXSXXOOOOOXX
        XXXXXXXXXXXXXXXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXXXXXXXXX
        XXOOOOOOOOOPFX
        XXDXXXXXXXOOOX
        XXXXXXXXXXXXXX
        XXXXXOOOOOOXFX
        XSOOOOXOXXOOOX
        XXXXXXXXXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXXXXXXXXX
        XXXXXOOOOOOFXX
        XXOOOXXXXXXXXX
        XXOGOOOOOOOXXX
        XXODXPPXXXFOOX
        XXXXXOOOOOOXOX
        XSSSOOOOOXXXGX
        XXXXXXXXXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXXXXXXXXX
        XSOXOOOXPGXPFX
        XXOOOXOOOOPOOX
        XXXXXXXXXOOOXX
        XFXOOOOPXXXXXX
        XOOOXXDPXPOOOX
        XXXXXXOOOOXXHX
        XXOOOXXXXXXXXX
        XOOPOOOOXOOOXX
        XGPXHPXOOOXOSX
        XXXXXXXXXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXXXXXXXXXXX
        XSSOOSOXOOSOOSSX
        XOOOOOOSOOOOOOOX
        XSSXXXXXXXXXXOOX
        XOOXOOOOOOOOXOOX
        XOOOOXXOOXXOOOOX
        XOOOOXFOGPXOOSSX
        XSSOOXDGPFXOOOOX
        XOOXXXXXXXXXXOOX
        XOOXOSOOOOSOXOOX
        XSSOOOOSOOOOOSSX
        XSSOOXOSOOXOOSSX
        XXXXXXXXXXXXXXXX
    """.trimIndent()),
    PuzzleDefinition("""
        XXXXXXX
        XXXDXXX
        XXXOXXX
        XXXVXXX
        XXXOXXX
        XXXSXXX
        XXXXXXX
    """.trimIndent(),
        listOf(
            VanishingWalkwayPattern(
                WALKWAY, WALKWAY, PIT
            )
        )
    )
)
